//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Detail
    {
        public int ItemId { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
